In [36]:
import pandas as pd
import pyreadstat

# Load SAS files
main, main_meta = pyreadstat.read_sas7bdat('c32pumfm.sas7bdat')

In [37]:
print('=== main.sas7bdat ===')
print(f'Shape: {main.shape}')
print(f'\nColumn labels:')
for col, label in main_meta.column_names_to_labels.items():
    print(f'  {col}: {label}')
print(f'\ndtypes:\n{main.dtypes}')
print(f'\nNull counts:\n{main.isnull().sum()}')
main.head()

=== main.sas7bdat ===
Shape: (20258, 1071)

Column labels:
  PUMFID: None
  WGHT_PER: None
  DV_PROXY: None
  AGEGR10: None
  SEX: None
  MARSTAT: None
  PHSDFLG: None
  AGEPRGR0: None
  SEXPR: None
  PRTYPEGR: None
  AGECXRYG: None
  AGEHSDYC: None
  CXRFLAG: None
  CHRNHSDC: None
  CXRTIME6: None
  CHH0014C: None
  SENFLAG: None
  LIVARR08: None
  LIVARRSN: None
  HSDSIZEC: None
  MULTIGEN: None
  LUC_RST: None
  PRV: None
  NLC_100C: None
  LMAM_01: None
  LMAM_02: None
  LPY_01: None
  LPY_02GR: None
  REW_10: None
  CAR_110: None
  CAR_115: None
  PRA_10GR: None
  PRA_15: None
  ARE_10: None
  ARE_20: None
  ARE_30: None
  ARE_40: None
  ARE_50: None
  ARE_60: None
  ARE_70: None
  ARE_80: None
  CARUNPAI: None
  CARPAID: None
  CARBOTH: None
  HAR_10C: None
  CRGVAGGR: None
  NPA_10C: None
  RPA_10C: None
  RPA_20C: None
  RPA_30C: None
  TPA_10C: None
  TPA_15C: None
  TPA_20C: None
  TPA_30C: None
  TPA_40C: None
  TPA_50C: None
  APA_10C: None
  APA_20C: None
  APA_30C: None
  APA_40C: None
  APA_50C: None
  RES_10: None
  PAA_05: None
  PAA_10: None
  PAA_20: None
  PAA_30: None
  PAA_40: None
  PAA_50: None
  PAA_60: None
  PAA_70: None
  PAA_80: None
  PAA_90: None
  DPA_10: None
  CNR_10: None
  DVCNR20: None
  PHP_10: None
  PHF_10: None
  BFP_10: None
  BFP_20: None
  NFA_10: None
  NFA_30: None
  NFA_50: None
  NFA_60: None
  NFA_70A: None
  NFA_70B: None
  NFA_70C: None
  NFA_70D: None
  PGN_25: None
  PGG10GR: None
  PGW_10: None
  PGW_20: None
  APGS_BEG: None
  SRE_10: None
  SRE_20GR: None
  DFA_10: None
  PGD_10: None
  PGU_10: None
  PGU_20: None
  PGH_10: None
  PGH_20: None
  AGT_10: None
  AGT_20: None
  AGT_30: None
  AGT_40: None
  AGI_10: None
  AGI_20: None
  AGI_30: None
  AGI_40: None
  AGO_10: None
  AGO_20: None
  AGO_30C: None
  AGO_40: None
  AGP_10: None
  AGP_20: None
  AGP_30C: None
  AGP_40: None
  AGM_10: None
  AGM_20: None
  AGM_30C: None
  AGM_40: None
  AGS_10: None
  AGS_20: None
  AGS_30C: None
  AGS_40: None
  AGB_10: None
  AGB_20: None
  AGB_30C: None
  AGB_40: None
  AGV_10: None
  AGV_40: None
  AGX_10: None
  AGX_40: None
  ICG_110: None
  ICG_115: None
  APR_10: None
  APR_20: None
  APR_30: None
  APR_40: None
  APR_50: None
  APR_60: None
  APR_70: None
  APR_80: None
  ICGCARGV: None
  HAP_10C: None
  PAR_10: None
  RRA_10C: None
  RRA_20C: None
  RRA_30C: None
  DPR_10C: None
  DPR_15C: None
  DPR_20C: None
  DPR_30C: None
  DPR_40C: None
  DPR_50C: None
  APX_10GR: None
  APX_20GR: None
  APX_30C: None
  APX_50GR: None
  RPE_10: None
  CRRCPAGR: None
  PRN_25: None
  PRN_Q30C: None
  PRN_40: None
  PRG10GR: None
  PRP10GR: None
  PRP_15: None
  PRW_10: None
  PRW_20: None
  APRS_BEG: None
  SPR_10: None
  SPR_20GR: None
  PRD_10: None
  PRU_10: None
  PRU_20: None
  PRH_10: None
  PRH_20: None
  ART_10: None
  ART_20: None
  ART_30: None
  ART_40: None
  ARI_10: None
  ARI_20: None
  ARI_30: None
  ARI_40: None
  ARO_10: None
  ARO_20: None
  ARO_30: None
  ARO_40: None
  ARP_10: None
  ARP_20: None
  ARP_30: None
  ARP_40: None
  ARM_10: None
  ARM_20: None
  ARM_30C: None
  ARM_40: None
  ARS_10: None
  ARS_20: None
  ARS_30C: None
  ARS_40: None
  ARB_10: None
  ARB_20: None
  ARB_30C: None
  ARB_40: None
  ARV_10: None
  ARV_40: None
  ARX_10: None
  ARX_40: None
  CCP_10: None
  CCP_20: None
  DVCG120C: None
  RNA_10C: None
  RNA_20C: None
  RNA_30C: None
  RNA_40C: None
  DNA_10C: None
  DNA_15C: None
  DNA_18GR: None
  DVDNA20C: None
  DNA_31C: None
  DNA_32C: None
  DNA_33C: None
  DNA_34C: None
  DNA_35C: None
  DNA_40C: None
  ROA_05: None
  ROA_10GR: None
  DOA_20: None
  DOA_30C: None
  HPO_10: None
  HRA_10: None
  ACD_10: None
  ACD_20: None
  ACD_30: None
  ACD_40: None
  ACD_50: None
  ACD_60: None
  ACD_70: None
  ACD_80: None
  ACD_90: None
  OAC_20: None
  OAC_30A: None
  OAC_30B: None
  OAC_30C: None
  OAC_30D: None
  OAC_30E: None
  OAC_30F: None
  OAC_30G: None
  OAC_30H: None
  CGH_100: None
  CGH_110: None
  CGH_120C: None
  AGEBEG1C: None
  AGEEND1C: None
  AGEBEG2C: None
  AGEEND2C: None
  CGI125_1: None
  CGI125_2: None
  CGI125_3: None
  CGI125_4: None
  CGI125_5: None
  CGI130G1: None
  CGI130G2: None
  CGE_100: None
  CGE_150: None
  CPE_20: None
  PEH_10: None
  CEH_10: None
  CEH_20: None
  CEH_30: None
  CEH_40: None
  CEH_50: None
  CEH_60: None
  CEH_70: None
  CCL_10: None
  CCL_20: None
  ICL_100: None
  ICL_110: None
  ICL_120: None
  ICL_130: None
  ICL_135: None
  ICL_140: None
  ICL_150: None
  ICL_152: None
  ICL_154: None
  ICL_160: None
  ICL_170: None
  ICL_180: None
  ICL_210: None
  ICB_10: None
  ICB_15: None
  ICB_20: None
  ICB_25: None
  ICB_30: None
  ICB_35GR: None
  ICB_40: None
  ICB_45: None
  ICP_10: None
  ICP_15: None
  ICP_20: None
  ICP_25: None
  ICP_30: None
  ICP_35: None
  ICP_40: None
  ICP_50: None
  ICP_60: None
  ICP_70: None
  ICS_10: None
  ICS_20: None
  ICS_30: None
  ICS_40: None
  FIS_10A: None
  FIS_10B: None
  FIS_10C: None
  FIS_10D: None
  FIS_10E: None
  FIS_10F: None
  FIS_10G: None
  FIS_10H: None
  FIS_10I: None
  CRH_10: None
  CRH_20: None
  CRH_30: None
  CRH_35: None
  CRH_40: None
  CRH_50: None
  CRH_60: None
  CRH_70: None
  CRH_80: None
  CRH_90: None
  CMC_10: None
  CMC_20A: None
  CMC_20B: None
  CMC_20C: None
  CMC_20D: None
  CMC_20E: None
  CMC_20F: None
  CMC_20G: None
  CMC_30: None
  ICF_210: None
  ICF_220: None
  ICF_230: None
  ICF_240: None
  ICF_250: None
  ICF_260: None
  HOME_EXP: None
  HLTH_EXP: None
  HELP_EXP: None
  TRNS_EXP: None
  AID_EXP: None
  MED_EXP: None
  ICF2_270: None
  ICF2273C: None
  ICF2_280: None
  ICF2_290: None
  ICF2_300: None
  ICF2_310: None
  ICF2_320: None
  ICF2_330: None
  ICF2_340: None
  ICF2_350: None
  ESC1_01: None
  EDM_01_1: None
  EDM_01_2: None
  EDM_01_3: None
  EDM_02: None
  EHG3_01: None
  EHG3_02: None
  EHG3_03: None
  EHG3_04: None
  EHG3_05: None
  ICE_20: None
  ICE_30: None
  ICE_50: None
  COW_10: None
  WTI_110: None
  WTI120GR: None
  WTI_130: None
  NAIC17CY: None
  NOC1610: None
  UCA_10: None
  NWE_110: None
  UHW_16GR: None
  UWS230GR: None
  TOE_240: None
  TOE_241: None
  FWA_120: None
  FWA_132: None
  FWA_133: None
  FWA_134: None
  FWA_136: None
  FWA_137: None
  FWA_150: None
  WLB_10: None
  WLB_20: None
  SRC_10: None
  SRC_20A: None
  SRC_20B: None
  SRC_20C: None
  SRC_20D: None
  SRC_20E: None
  SRC_20F: None
  SRC_20G: None
  SRC_20H: None
  ITL_10C: None
  ITL_20: None
  ITL_30: None
  ITL_40C: None
  ITL_50: None
  ITL_51: None
  ITA_10C: None
  ITA_20: None
  ITA_30: None
  ITE_10: None
  ITE_20: None
  ITE_30A: None
  ITE_30B: None
  ITE_30C: None
  ITE_30D: None
  ITE_30E: None
  ITO_10: None
  ITO_20: None
  ITO_25: None
  ITO_26: None
  INE_10: None
  INE_20: None
  INE_30: None
  INE_41A: None
  INE_41B: None
  INE_41C: None
  INE_41D: None
  INE_41E: None
  IPL_05: None
  IPL_10: None
  IPL_20: None
  IPA_10: None
  IPA_20: None
  IPA_21C: None
  IPA_22C: None
  IPA_23C: None
  IPA_24C: None
  IPA_30: None
  IPA_35C: None
  IPE_10GR: None
  IPE_30A: None
  IPE_30B: None
  IPE_30C: None
  IPE_30D: None
  IPE_30E: None
  IPE_30F: None
  IPE_30G: None
  IPO_10GR: None
  IPO_20GR: None
  IPR_10: None
  IPR_20: None
  IPR_30: None
  IPR_40: None
  IPR_44C: None
  DWELC: None
  ODR_10: None
  ODR_20: None
  LRD_10: None
  LIVE_NEI: None
  LIVLOCGR: None
  QIN_10: None
  QIN_20: None
  QIN_30: None
  QIN_40: None
  PTN_10: None
  AHR_100: None
  AHR_110: None
  AHR_120: None
  AHR_130: None
  AHR_140: None
  AHR_150: None
  AHR_160: None
  AHR_200: None
  SRH_110: None
  SRH_115: None
  HEH_100: None
  PHS_10C: None
  PHS_20: None
  LSR_110: None
  SRS_10: None
  SLP_110: None
  SLP_120: None
  FLG_310: None
  FLG_320: None
  FLG_330: None
  FLG_340: None
  FLG_350: None
  FLG_360: None
  EMO_10: None
  DDIS_FL: None
  DVIS_FL: None
  DHEAR_FL: None
  DMOB_FL: None
  DFLEX_FL: None
  DDEX_FL: None
  DPAIN_FL: None
  DLRN_FL: None
  DDEV_FL: None
  DMEM_FL: None
  DMENT_FL: None
  DUNK_FL: None
  DTYPER: None
  CHC_100: None
  CHC_110A: None
  CHC_110B: None
  CHC_110C: None
  CHC_110D: None
  CHC_110E: None
  CHC_110F: None
  CHC_110G: None
  CHC_110H: None
  CHC_110I: None
  CHC_110J: None
  CHC_110K: None
  CHC_110L: None
  CHC_110M: None
  CHC_110N: None
  CHC_110O: None
  CHC_110P: None
  CHC_110Q: None
  CHC_110R: None
  CHC_110S: None
  CHC_110T: None
  CHC_110U: None
  CHC_110V: None
  CHC_110Y: None
  CHC110AB: None
  CHC110AC: None
  DVCHC110: None
  BRTHCAN: None
  BRTHPRVC: None
  BRTHMACR: None
  BRTHSUB: None
  YRARRI: None
  BPR_16: None
  YRLNDIMM: None
  AGARRGRC: None
  ALNDIMGC: None
  AMB_01_1: None
  AMB_01_2: None
  AMB_01_3: None
  AMB_01_4: None
  PG_01A: None
  PG_01B: None
  PG_01C: None
  PG_01D: None
  PG_01E: None
  PG_01F: None
  PG_01G: None
  PG_01H: None
  PG_01I: None
  PG_01J: None
  PG_01K: None
  PG_01L: None
  VISMIN: None
  REE_02: None
  REE_03: None
  RLR_110: None
  RELIGFLG: None
  LAN_01: None
  LANHOMEC: None
  LANHMULT: None
  LANMT: None
  LANMTMUL: None
  VET_120: None
  TTLINCG1: None
  FAMINCG1: None
  WTBS_001: None
  WTBS_002: None
  WTBS_003: None
  WTBS_004: None
  WTBS_005: None
  WTBS_006: None
  WTBS_007: None
  WTBS_008: None
  WTBS_009: None
  WTBS_010: None
  WTBS_011: None
  WTBS_012: None
  WTBS_013: None
  WTBS_014: None
  WTBS_015: None
  WTBS_016: None
  WTBS_017: None
  WTBS_018: None
  WTBS_019: None
  WTBS_020: None
  WTBS_021: None
  WTBS_022: None
  WTBS_023: None
  WTBS_024: None
  WTBS_025: None
  WTBS_026: None
  WTBS_027: None
  WTBS_028: None
  WTBS_029: None
  WTBS_030: None
  WTBS_031: None
  WTBS_032: None
  WTBS_033: None
  WTBS_034: None
  WTBS_035: None
  WTBS_036: None
  WTBS_037: None
  WTBS_038: None
  WTBS_039: None
  WTBS_040: None
  WTBS_041: None
  WTBS_042: None
  WTBS_043: None
  WTBS_044: None
  WTBS_045: None
  WTBS_046: None
  WTBS_047: None
  WTBS_048: None
  WTBS_049: None
  WTBS_050: None
  WTBS_051: None
  WTBS_052: None
  WTBS_053: None
  WTBS_054: None
  WTBS_055: None
  WTBS_056: None
  WTBS_057: None
  WTBS_058: None
  WTBS_059: None
  WTBS_060: None
  WTBS_061: None
  WTBS_062: None
  WTBS_063: None
  WTBS_064: None
  WTBS_065: None
  WTBS_066: None
  WTBS_067: None
  WTBS_068: None
  WTBS_069: None
  WTBS_070: None
  WTBS_071: None
  WTBS_072: None
  WTBS_073: None
  WTBS_074: None
  WTBS_075: None
  WTBS_076: None
  WTBS_077: None
  WTBS_078: None
  WTBS_079: None
  WTBS_080: None
  WTBS_081: None
  WTBS_082: None
  WTBS_083: None
  WTBS_084: None
  WTBS_085: None
  WTBS_086: None
  WTBS_087: None
  WTBS_088: None
  WTBS_089: None
  WTBS_090: None
  WTBS_091: None
  WTBS_092: None
  WTBS_093: None
  WTBS_094: None
  WTBS_095: None
  WTBS_096: None
  WTBS_097: None
  WTBS_098: None
  WTBS_099: None
  WTBS_100: None
  WTBS_101: None
  WTBS_102: None
  WTBS_103: None
  WTBS_104: None
  WTBS_105: None
  WTBS_106: None
  WTBS_107: None
  WTBS_108: None
  WTBS_109: None
  WTBS_110: None
  WTBS_111: None
  WTBS_112: None
  WTBS_113: None
  WTBS_114: None
  WTBS_115: None
  WTBS_116: None
  WTBS_117: None
  WTBS_118: None
  WTBS_119: None
  WTBS_120: None
  WTBS_121: None
  WTBS_122: None
  WTBS_123: None
  WTBS_124: None
  WTBS_125: None
  WTBS_126: None
  WTBS_127: None
  WTBS_128: None
  WTBS_129: None
  WTBS_130: None
  WTBS_131: None
  WTBS_132: None
  WTBS_133: None
  WTBS_134: None
  WTBS_135: None
  WTBS_136: None
  WTBS_137: None
  WTBS_138: None
  WTBS_139: None
  WTBS_140: None
  WTBS_141: None
  WTBS_142: None
  WTBS_143: None
  WTBS_144: None
  WTBS_145: None
  WTBS_146: None
  WTBS_147: None
  WTBS_148: None
  WTBS_149: None
  WTBS_150: None
  WTBS_151: None
  WTBS_152: None
  WTBS_153: None
  WTBS_154: None
  WTBS_155: None
  WTBS_156: None
  WTBS_157: None
  WTBS_158: None
  WTBS_159: None
  WTBS_160: None
  WTBS_161: None
  WTBS_162: None
  WTBS_163: None
  WTBS_164: None
  WTBS_165: None
  WTBS_166: None
  WTBS_167: None
  WTBS_168: None
  WTBS_169: None
  WTBS_170: None
  WTBS_171: None
  WTBS_172: None
  WTBS_173: None
  WTBS_174: None
  WTBS_175: None
  WTBS_176: None
  WTBS_177: None
  WTBS_178: None
  WTBS_179: None
  WTBS_180: None
  WTBS_181: None
  WTBS_182: None
  WTBS_183: None
  WTBS_184: None
  WTBS_185: None
  WTBS_186: None
  WTBS_187: None
  WTBS_188: None
  WTBS_189: None
  WTBS_190: None
  WTBS_191: None
  WTBS_192: None
  WTBS_193: None
  WTBS_194: None
  WTBS_195: None
  WTBS_196: None
  WTBS_197: None
  WTBS_198: None
  WTBS_199: None
  WTBS_200: None
  WTBS_201: None
  WTBS_202: None
  WTBS_203: None
  WTBS_204: None
  WTBS_205: None
  WTBS_206: None
  WTBS_207: None
  WTBS_208: None
  WTBS_209: None
  WTBS_210: None
  WTBS_211: None
  WTBS_212: None
  WTBS_213: None
  WTBS_214: None
  WTBS_215: None
  WTBS_216: None
  WTBS_217: None
  WTBS_218: None
  WTBS_219: None
  WTBS_220: None
  WTBS_221: None
  WTBS_222: None
  WTBS_223: None
  WTBS_224: None
  WTBS_225: None
  WTBS_226: None
  WTBS_227: None
  WTBS_228: None
  WTBS_229: None
  WTBS_230: None
  WTBS_231: None
  WTBS_232: None
  WTBS_233: None
  WTBS_234: None
  WTBS_235: None
  WTBS_236: None
  WTBS_237: None
  WTBS_238: None
  WTBS_239: None
  WTBS_240: None
  WTBS_241: None
  WTBS_242: None
  WTBS_243: None
  WTBS_244: None
  WTBS_245: None
  WTBS_246: None
  WTBS_247: None
  WTBS_248: None
  WTBS_249: None
  WTBS_250: None
  WTBS_251: None
  WTBS_252: None
  WTBS_253: None
  WTBS_254: None
  WTBS_255: None
  WTBS_256: None
  WTBS_257: None
  WTBS_258: None
  WTBS_259: None
  WTBS_260: None
  WTBS_261: None
  WTBS_262: None
  WTBS_263: None
  WTBS_264: None
  WTBS_265: None
  WTBS_266: None
  WTBS_267: None
  WTBS_268: None
  WTBS_269: None
  WTBS_270: None
  WTBS_271: None
  WTBS_272: None
  WTBS_273: None
  WTBS_274: None
  WTBS_275: None
  WTBS_276: None
  WTBS_277: None
  WTBS_278: None
  WTBS_279: None
  WTBS_280: None
  WTBS_281: None
  WTBS_282: None
  WTBS_283: None
  WTBS_284: None
  WTBS_285: None
  WTBS_286: None
  WTBS_287: None
  WTBS_288: None
  WTBS_289: None
  WTBS_290: None
  WTBS_291: None
  WTBS_292: None
  WTBS_293: None
  WTBS_294: None
  WTBS_295: None
  WTBS_296: None
  WTBS_297: None
  WTBS_298: None
  WTBS_299: None
  WTBS_300: None
  WTBS_301: None
  WTBS_302: None
  WTBS_303: None
  WTBS_304: None
  WTBS_305: None
  WTBS_306: None
  WTBS_307: None
  WTBS_308: None
  WTBS_309: None
  WTBS_310: None
  WTBS_311: None
  WTBS_312: None
  WTBS_313: None
  WTBS_314: None
  WTBS_315: None
  WTBS_316: None
  WTBS_317: None
  WTBS_318: None
  WTBS_319: None
  WTBS_320: None
  WTBS_321: None
  WTBS_322: None
  WTBS_323: None
  WTBS_324: None
  WTBS_325: None
  WTBS_326: None
  WTBS_327: None
  WTBS_328: None
  WTBS_329: None
  WTBS_330: None
  WTBS_331: None
  WTBS_332: None
  WTBS_333: None
  WTBS_334: None
  WTBS_335: None
  WTBS_336: None
  WTBS_337: None
  WTBS_338: None
  WTBS_339: None
  WTBS_340: None
  WTBS_341: None
  WTBS_342: None
  WTBS_343: None
  WTBS_344: None
  WTBS_345: None
  WTBS_346: None
  WTBS_347: None
  WTBS_348: None
  WTBS_349: None
  WTBS_350: None
  WTBS_351: None
  WTBS_352: None
  WTBS_353: None
  WTBS_354: None
  WTBS_355: None
  WTBS_356: None
  WTBS_357: None
  WTBS_358: None
  WTBS_359: None
  WTBS_360: None
  WTBS_361: None
  WTBS_362: None
  WTBS_363: None
  WTBS_364: None
  WTBS_365: None
  WTBS_366: None
  WTBS_367: None
  WTBS_368: None
  WTBS_369: None
  WTBS_370: None
  WTBS_371: None
  WTBS_372: None
  WTBS_373: None
  WTBS_374: None
  WTBS_375: None
  WTBS_376: None
  WTBS_377: None
  WTBS_378: None
  WTBS_379: None
  WTBS_380: None
  WTBS_381: None
  WTBS_382: None
  WTBS_383: None
  WTBS_384: None
  WTBS_385: None
  WTBS_386: None
  WTBS_387: None
  WTBS_388: None
  WTBS_389: None
  WTBS_390: None
  WTBS_391: None
  WTBS_392: None
  WTBS_393: None
  WTBS_394: None
  WTBS_395: None
  WTBS_396: None
  WTBS_397: None
  WTBS_398: None
  WTBS_399: None
  WTBS_400: None
  WTBS_401: None
  WTBS_402: None
  WTBS_403: None
  WTBS_404: None
  WTBS_405: None
  WTBS_406: None
  WTBS_407: None
  WTBS_408: None
  WTBS_409: None
  WTBS_410: None
  WTBS_411: None
  WTBS_412: None
  WTBS_413: None
  WTBS_414: None
  WTBS_415: None
  WTBS_416: None
  WTBS_417: None
  WTBS_418: None
  WTBS_419: None
  WTBS_420: None
  WTBS_421: None
  WTBS_422: None
  WTBS_423: None
  WTBS_424: None
  WTBS_425: None
  WTBS_426: None
  WTBS_427: None
  WTBS_428: None
  WTBS_429: None
  WTBS_430: None
  WTBS_431: None
  WTBS_432: None
  WTBS_433: None
  WTBS_434: None
  WTBS_435: None
  WTBS_436: None
  WTBS_437: None
  WTBS_438: None
  WTBS_439: None
  WTBS_440: None
  WTBS_441: None
  WTBS_442: None
  WTBS_443: None
  WTBS_444: None
  WTBS_445: None
  WTBS_446: None
  WTBS_447: None
  WTBS_448: None
  WTBS_449: None
  WTBS_450: None
  WTBS_451: None
  WTBS_452: None
  WTBS_453: None
  WTBS_454: None
  WTBS_455: None
  WTBS_456: None
  WTBS_457: None
  WTBS_458: None
  WTBS_459: None
  WTBS_460: None
  WTBS_461: None
  WTBS_462: None
  WTBS_463: None
  WTBS_464: None
  WTBS_465: None
  WTBS_466: None
  WTBS_467: None
  WTBS_468: None
  WTBS_469: None
  WTBS_470: None
  WTBS_471: None
  WTBS_472: None
  WTBS_473: None
  WTBS_474: None
  WTBS_475: None
  WTBS_476: None
  WTBS_477: None
  WTBS_478: None
  WTBS_479: None
  WTBS_480: None
  WTBS_481: None
  WTBS_482: None
  WTBS_483: None
  WTBS_484: None
  WTBS_485: None
  WTBS_486: None
  WTBS_487: None
  WTBS_488: None
  WTBS_489: None
  WTBS_490: None
  WTBS_491: None
  WTBS_492: None
  WTBS_493: None
  WTBS_494: None
  WTBS_495: None
  WTBS_496: None
  WTBS_497: None
  WTBS_498: None
  WTBS_499: None
  WTBS_500: None

dtypes:
PUMFID      float64
WGHT_PER    float64
DV_PROXY    float64
AGEGR10     float64
SEX         float64
             ...
WTBS_496    float64
WTBS_497    float64
WTBS_498    float64
WTBS_499    float64
WTBS_500    float64
Length: 1071, dtype: object

Null counts:
PUMFID      0
WGHT_PER    0
DV_PROXY    0
AGEGR10     0
SEX         0
           ..
WTBS_496    0
WTBS_497    0
WTBS_498    0
WTBS_499    0
WTBS_500    0
Length: 1071, dtype: int64

,PUMFID,WGHT_PER,DV_PROXY,AGEGR10,SEX,MARSTAT,PHSDFLG,AGEPRGR0,SEXPR,PRTYPEGR,...,WTBS_491,WTBS_492,WTBS_493,WTBS_494,WTBS_495,WTBS_496,WTBS_497,WTBS_498,WTBS_499,WTBS_500
0,1.0,10429.6532,2.0,1.0,2.0,6.0,2.0,96.0,6.0,6.0,...,13958.7955,0.0000,15235.1417,0.0000,0.0000,0.0000,7636.5763,0.0000,20156.7316,12070.4628
1,2.0,1488.7196,2.0,6.0,1.0,1.0,1.0,7.0,2.0,1.0,...,2293.9604,1878.5542,1269.8145,1768.0881,0.0000,1385.7926,1905.8713,0.0000,0.0000,4034.4182
2,3.0,1190.9425,2.0,6.0,1.0,5.0,2.0,96.0,6.0,6.0,...,1056.2125,2364.2873,2418.4156,1140.8678,1151.9689,2600.7988,1096.2847,0.0000,1160.3501,1012.4831
3,4.0,165.3536,2.0,6.0,2.0,1.0,1.0,6.0,1.0,1.0,...,0.0000,781.9517,329.1084,396.3570,0.0000,594.7097,0.0000,0.0000,621.7721,0.0000
4,5.0,2518.6703,2.0,3.0,2.0,1.0,1.0,3.0,1.0,1.0,...,2595.4758,3763.7464,0.0000,3464.0331,2518.0673,0.0000,8656.5904,1968.5295,0.0000,2384.1470

In [38]:
# Summary stats for numeric columns
print('=== main describe ===')
display(main.describe())
print('\n=== maindata describe ===')
display(main.describe())

=== main describe ===

,PUMFID,WGHT_PER,DV_PROXY,AGEGR10,SEX,MARSTAT,PHSDFLG,AGEPRGR0,SEXPR,PRTYPEGR,...,WTBS_491,WTBS_492,WTBS_493,WTBS_494,WTBS_495,WTBS_496,WTBS_497,WTBS_498,WTBS_499,WTBS_500
count,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.00000,20258.000000,...,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000
mean,10129.500000,1518.174772,1.981439,4.487314,1.563876,2.874272,1.426153,43.509330,3.40468,3.239806,...,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772
std,5848.125212,1814.000649,0.134970,1.699978,0.495915,4.431455,0.494529,45.259476,2.26837,2.400460,...,2871.400334,2837.865040,2900.433725,2895.944167,2900.871075,2934.725123,2889.876392,2914.951611,2955.079876,2903.376400
min,1.000000,10.354100,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5065.250000,452.102300,2.000000,3.000000,1.000000,1.000000,1.000000,4.000000,1.00000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10129.500000,1039.674700,2.000000,5.000000,2.000000,2.000000,1.000000,6.000000,2.00000,2.000000,...,517.491700,498.752050,501.983400,499.363000,505.872400,491.492300,501.878500,484.312350,523.022750,489.835450
75%,15193.750000,1892.145225,2.000000,6.000000,2.000000,5.000000,2.000000,96.000000,6.00000,6.000000,...,1914.294575,1867.527300,1873.256875,1900.100100,1892.858875,1858.605100,1860.981075,1864.010125,1879.388375,1876.777925
max,20258.000000,30702.105200,2.000000,7.000000,2.000000,99.000000,2.000000,99.000000,6.00000,6.000000,...,84147.543300,55460.877700,55342.297500,75955.616300,57021.799500,73161.390000,58049.098800,59769.746900,75741.719100,64696.180200

=== maindata describe ===

,PUMFID,WGHT_PER,DV_PROXY,AGEGR10,SEX,MARSTAT,PHSDFLG,AGEPRGR0,SEXPR,PRTYPEGR,...,WTBS_491,WTBS_492,WTBS_493,WTBS_494,WTBS_495,WTBS_496,WTBS_497,WTBS_498,WTBS_499,WTBS_500
count,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.00000,20258.000000,...,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000,20258.000000
mean,10129.500000,1518.174772,1.981439,4.487314,1.563876,2.874272,1.426153,43.509330,3.40468,3.239806,...,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772,1518.174772
std,5848.125212,1814.000649,0.134970,1.699978,0.495915,4.431455,0.494529,45.259476,2.26837,2.400460,...,2871.400334,2837.865040,2900.433725,2895.944167,2900.871075,2934.725123,2889.876392,2914.951611,2955.079876,2903.376400
min,1.000000,10.354100,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5065.250000,452.102300,2.000000,3.000000,1.000000,1.000000,1.000000,4.000000,1.00000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10129.500000,1039.674700,2.000000,5.000000,2.000000,2.000000,1.000000,6.000000,2.00000,2.000000,...,517.491700,498.752050,501.983400,499.363000,505.872400,491.492300,501.878500,484.312350,523.022750,489.835450
75%,15193.750000,1892.145225,2.000000,6.000000,2.000000,5.000000,2.000000,96.000000,6.00000,6.000000,...,1914.294575,1867.527300,1873.256875,1900.100100,1892.858875,1858.605100,1860.981075,1864.010125,1879.388375,1876.777925
max,20258.000000,30702.105200,2.000000,7.000000,2.000000,99.000000,2.000000,99.000000,6.00000,6.000000,...,84147.543300,55460.877700,55342.297500,75955.616300,57021.799500,73161.390000,58049.098800,59769.746900,75741.719100,64696.180200

In [39]:
# removed WTBS_ columns since they are not relevant to our analysis
main_clean = main.drop(columns=[c for c in main.columns if c.startswith('WTBS_')])

print(main_clean.shape)

print([c for c in main_clean.columns if c.startswith('WTBS_')])

(20258, 571)
[]

In [40]:
for col in main_clean.columns:
    print(col)

PUMFID
WGHT_PER
DV_PROXY
AGEGR10
SEX
MARSTAT
PHSDFLG
AGEPRGR0
SEXPR
PRTYPEGR
AGECXRYG
AGEHSDYC
CXRFLAG
CHRNHSDC
CXRTIME6
CHH0014C
SENFLAG
LIVARR08
LIVARRSN
HSDSIZEC
MULTIGEN
LUC_RST
PRV
NLC_100C
LMAM_01
LMAM_02
LPY_01
LPY_02GR
REW_10
CAR_110
CAR_115
PRA_10GR
PRA_15
ARE_10
ARE_20
ARE_30
ARE_40
ARE_50
ARE_60
ARE_70
ARE_80
CARUNPAI
CARPAID
CARBOTH
HAR_10C
CRGVAGGR
NPA_10C
RPA_10C
RPA_20C
RPA_30C
TPA_10C
TPA_15C
TPA_20C
TPA_30C
TPA_40C
TPA_50C
APA_10C
APA_20C
APA_30C
APA_40C
APA_50C
RES_10
PAA_05
PAA_10
PAA_20
PAA_30
PAA_40
PAA_50
PAA_60
PAA_70
PAA_80
PAA_90
DPA_10
CNR_10
DVCNR20
PHP_10
PHF_10
BFP_10
BFP_20
NFA_10
NFA_30
NFA_50
NFA_60
NFA_70A
NFA_70B
NFA_70C
NFA_70D
PGN_25
PGG10GR
PGW_10
PGW_20
APGS_BEG
SRE_10
SRE_20GR
DFA_10
PGD_10
PGU_10
PGU_20
PGH_10
PGH_20
AGT_10
AGT_20
AGT_30
AGT_40
AGI_10
AGI_20
AGI_30
AGI_40
AGO_10
AGO_20
AGO_30C
AGO_40
AGP_10
AGP_20
AGP_30C
AGP_40
AGM_10
AGM_20
AGM_30C
AGM_40
AGS_10
AGS_20
AGS_30C
AGS_40
AGB_10
AGB_20
AGB_30C
AGB_40
AGV_10
AGV_40
AGX_10
AGX_40
ICG_110
ICG_115
APR_10
APR_20
APR_30
APR_40
APR_50
APR_60
APR_70
APR_80
ICGCARGV
HAP_10C
PAR_10
RRA_10C
RRA_20C
RRA_30C
DPR_10C
DPR_15C
DPR_20C
DPR_30C
DPR_40C
DPR_50C
APX_10GR
APX_20GR
APX_30C
APX_50GR
RPE_10
CRRCPAGR
PRN_25
PRN_Q30C
PRN_40
PRG10GR
PRP10GR
PRP_15
PRW_10
PRW_20
APRS_BEG
SPR_10
SPR_20GR
PRD_10
PRU_10
PRU_20
PRH_10
PRH_20
ART_10
ART_20
ART_30
ART_40
ARI_10
ARI_20
ARI_30
ARI_40
ARO_10
ARO_20
ARO_30
ARO_40
ARP_10
ARP_20
ARP_30
ARP_40
ARM_10
ARM_20
ARM_30C
ARM_40
ARS_10
ARS_20
ARS_30C
ARS_40
ARB_10
ARB_20
ARB_30C
ARB_40
ARV_10
ARV_40
ARX_10
ARX_40
CCP_10
CCP_20
DVCG120C
RNA_10C
RNA_20C
RNA_30C
RNA_40C
DNA_10C
DNA_15C
DNA_18GR
DVDNA20C
DNA_31C
DNA_32C
DNA_33C
DNA_34C
DNA_35C
DNA_40C
ROA_05
ROA_10GR
DOA_20
DOA_30C
HPO_10
HRA_10
ACD_10
ACD_20
ACD_30
ACD_40
ACD_50
ACD_60
ACD_70
ACD_80
ACD_90
OAC_20
OAC_30A
OAC_30B
OAC_30C
OAC_30D
OAC_30E
OAC_30F
OAC_30G
OAC_30H
CGH_100
CGH_110
CGH_120C
AGEBEG1C
AGEEND1C
AGEBEG2C
AGEEND2C
CGI125_1
CGI125_2
CGI125_3
CGI125_4
CGI125_5
CGI130G1
CGI130G2
CGE_100
CGE_150
CPE_20
PEH_10
CEH_10
CEH_20
CEH_30
CEH_40
CEH_50
CEH_60
CEH_70
CCL_10
CCL_20
ICL_100
ICL_110
ICL_120
ICL_130
ICL_135
ICL_140
ICL_150
ICL_152
ICL_154
ICL_160
ICL_170
ICL_180
ICL_210
ICB_10
ICB_15
ICB_20
ICB_25
ICB_30
ICB_35GR
ICB_40
ICB_45
ICP_10
ICP_15
ICP_20
ICP_25
ICP_30
ICP_35
ICP_40
ICP_50
ICP_60
ICP_70
ICS_10
ICS_20
ICS_30
ICS_40
FIS_10A
FIS_10B
FIS_10C
FIS_10D
FIS_10E
FIS_10F
FIS_10G
FIS_10H
FIS_10I
CRH_10
CRH_20
CRH_30
CRH_35
CRH_40
CRH_50
CRH_60
CRH_70
CRH_80
CRH_90
CMC_10
CMC_20A
CMC_20B
CMC_20C
CMC_20D
CMC_20E
CMC_20F
CMC_20G
CMC_30
ICF_210
ICF_220
ICF_230
ICF_240
ICF_250
ICF_260
HOME_EXP
HLTH_EXP
HELP_EXP
TRNS_EXP
AID_EXP
MED_EXP
ICF2_270
ICF2273C
ICF2_280
ICF2_290
ICF2_300
ICF2_310
ICF2_320
ICF2_330
ICF2_340
ICF2_350
ESC1_01
EDM_01_1
EDM_01_2
EDM_01_3
EDM_02
EHG3_01
EHG3_02
EHG3_03
EHG3_04
EHG3_05
ICE_20
ICE_30
ICE_50
COW_10
WTI_110
WTI120GR
WTI_130
NAIC17CY
NOC1610
UCA_10
NWE_110
UHW_16GR
UWS230GR
TOE_240
TOE_241
FWA_120
FWA_132
FWA_133
FWA_134
FWA_136
FWA_137
FWA_150
WLB_10
WLB_20
SRC_10
SRC_20A
SRC_20B
SRC_20C
SRC_20D
SRC_20E
SRC_20F
SRC_20G
SRC_20H
ITL_10C
ITL_20
ITL_30
ITL_40C
ITL_50
ITL_51
ITA_10C
ITA_20
ITA_30
ITE_10
ITE_20
ITE_30A
ITE_30B
ITE_30C
ITE_30D
ITE_30E
ITO_10
ITO_20
ITO_25
ITO_26
INE_10
INE_20
INE_30
INE_41A
INE_41B
INE_41C
INE_41D
INE_41E
IPL_05
IPL_10
IPL_20
IPA_10
IPA_20
IPA_21C
IPA_22C
IPA_23C
IPA_24C
IPA_30
IPA_35C
IPE_10GR
IPE_30A
IPE_30B
IPE_30C
IPE_30D
IPE_30E
IPE_30F
IPE_30G
IPO_10GR
IPO_20GR
IPR_10
IPR_20
IPR_30
IPR_40
IPR_44C
DWELC
ODR_10
ODR_20
LRD_10
LIVE_NEI
LIVLOCGR
QIN_10
QIN_20
QIN_30
QIN_40
PTN_10
AHR_100
AHR_110
AHR_120
AHR_130
AHR_140
AHR_150
AHR_160
AHR_200
SRH_110
SRH_115
HEH_100
PHS_10C
PHS_20
LSR_110
SRS_10
SLP_110
SLP_120
FLG_310
FLG_320
FLG_330
FLG_340
FLG_350
FLG_360
EMO_10
DDIS_FL
DVIS_FL
DHEAR_FL
DMOB_FL
DFLEX_FL
DDEX_FL
DPAIN_FL
DLRN_FL
DDEV_FL
DMEM_FL
DMENT_FL
DUNK_FL
DTYPER
CHC_100
CHC_110A
CHC_110B
CHC_110C
CHC_110D
CHC_110E
CHC_110F
CHC_110G
CHC_110H
CHC_110I
CHC_110J
CHC_110K
CHC_110L
CHC_110M
CHC_110N
CHC_110O
CHC_110P
CHC_110Q
CHC_110R
CHC_110S
CHC_110T
CHC_110U
CHC_110V
CHC_110Y
CHC110AB
CHC110AC
DVCHC110
BRTHCAN
BRTHPRVC
BRTHMACR
BRTHSUB
YRARRI
BPR_16
YRLNDIMM
AGARRGRC
ALNDIMGC
AMB_01_1
AMB_01_2
AMB_01_3
AMB_01_4
PG_01A
PG_01B
PG_01C
PG_01D
PG_01E
PG_01F
PG_01G
PG_01H
PG_01I
PG_01J
PG_01K
PG_01L
VISMIN
REE_02
REE_03
RLR_110
RELIGFLG
LAN_01
LANHOMEC
LANHMULT
LANMT
LANMTMUL
VET_120
TTLINCG1
FAMINCG1

In [41]:
drop_exact = [
    'PUMFID',
    'WGHT_PER',
    'DV_PROXY',
    'EQFLAG',
    'SURVMNTH',
    'CXRFLAG',
    'DDEV_FL',
    'DDEX_FL'
]

drop_prefixes = ['WTBS_']
drop_module_prefixes = ['CAR', 'PRA', 'ARE', 'HAR', 'NPA', 'RPA', 'NFA', 'PG', 'AG']

cols_to_drop = []

for col in main_clean.columns:
    if col in drop_exact:
        cols_to_drop.append(col)
    elif any(col.startswith(prefix) for prefix in drop_prefixes):
        cols_to_drop.append(col)
    elif any(col.startswith(prefix) for prefix in drop_module_prefixes):
        cols_to_drop.append(col)

main_reduced = main_clean.drop(columns=cols_to_drop)

print("Dropped:", len(cols_to_drop))
print(cols_to_drop)
print(main_reduced.shape)

Dropped: 96
['PUMFID', 'WGHT_PER', 'DV_PROXY', 'AGEGR10', 'AGEPRGR0', 'AGECXRYG', 'AGEHSDYC', 'CXRFLAG', 'CAR_110', 'CAR_115', 'PRA_10GR', 'PRA_15', 'ARE_10', 'ARE_20', 'ARE_30', 'ARE_40', 'ARE_50', 'ARE_60', 'ARE_70', 'ARE_80', 'CARUNPAI', 'CARPAID', 'CARBOTH', 'HAR_10C', 'NPA_10C', 'RPA_10C', 'RPA_20C', 'RPA_30C', 'NFA_10', 'NFA_30', 'NFA_50', 'NFA_60', 'NFA_70A', 'NFA_70B', 'NFA_70C', 'NFA_70D', 'PGN_25', 'PGG10GR', 'PGW_10', 'PGW_20', 'PGD_10', 'PGU_10', 'PGU_20', 'PGH_10', 'PGH_20', 'AGT_10', 'AGT_20', 'AGT_30', 'AGT_40', 'AGI_10', 'AGI_20', 'AGI_30', 'AGI_40', 'AGO_10', 'AGO_20', 'AGO_30C', 'AGO_40', 'AGP_10', 'AGP_20', 'AGP_30C', 'AGP_40', 'AGM_10', 'AGM_20', 'AGM_30C', 'AGM_40', 'AGS_10', 'AGS_20', 'AGS_30C', 'AGS_40', 'AGB_10', 'AGB_20', 'AGB_30C', 'AGB_40', 'AGV_10', 'AGV_40', 'AGX_10', 'AGX_40', 'AGEBEG1C', 'AGEEND1C', 'AGEBEG2C', 'AGEEND2C', 'DDEX_FL', 'DDEV_FL', 'AGARRGRC', 'PG_01A', 'PG_01B', 'PG_01C', 'PG_01D', 'PG_01E', 'PG_01F', 'PG_01G', 'PG_01H', 'PG_01I', 'PG_01J', 'PG_01K', 'PG_01L']
(20258, 475)

In [ ]:
#NOT SURE ABOUT THE CODE FROM HERE ON OUT

candidate_targets = [
    'ICS_40',
    'FIS_10A', 'FIS_10H',
]

existing_targets = [c for c in candidate_targets if c in main_reduced.columns]
print("Existing target columns:", existing_targets)

Existing target columns: ['ICS_40', 'FIS_10A', 'FIS_10H']

In [43]:
import numpy as np
reserve_codes = [
    6, 9,
    96, 99,
    996, 999,
    9996, 9999,
    99996, 99999,
    999996, 999999
]

main_targets = main_reduced.copy()

for col in existing_targets:
    main_targets[col] = main_targets[col].replace(reserve_codes, np.nan)

In [44]:
burnout_items = [
    'ICS_40',
    'FIS_10A', 'FIS_10B', 'FIS_10C', 'FIS_10D',
    'FIS_10E', 'FIS_10F', 'FIS_10G', 'FIS_10H',
    'CRH_10', 'CRH_20', 'CRH_30'
]

burnout_items = [c for c in burnout_items if c in main_targets.columns]

main_targets['burnout_score'] = main_targets[burnout_items].mean(axis=1)

print("Burnout items used:", burnout_items)
print(main_targets['burnout_score'].describe())

Burnout items used: ['ICS_40', 'FIS_10A', 'FIS_10B', 'FIS_10C', 'FIS_10D', 'FIS_10E', 'FIS_10F', 'FIS_10G', 'FIS_10H', 'CRH_10', 'CRH_20', 'CRH_30']
count    5633.000000
mean        1.777244
std         0.439116
min         1.000000
25%         1.416667
50%         1.750000
75%         2.000000
max         4.000000
Name: burnout_score, dtype: float64

In [45]:
main_targets = main_targets[main_targets['burnout_score'].notna()].copy()

median_score = main_targets['burnout_score'].median()
main_targets['burnout_high'] = (main_targets['burnout_score'] >= median_score).astype(int)

print("Median cutoff:", median_score)
print(main_targets['burnout_high'].value_counts())

Median cutoff: 1.75
burnout_high
1    2943
0    2690
Name: count, dtype: int64

In [46]:
target_cols_to_remove = burnout_items + ['burnout_score', 'burnout_high']

X = main_targets.drop(columns=[c for c in target_cols_to_remove if c in main_targets.columns])
y_reg = main_targets['burnout_score']
y_clf = main_targets['burnout_high']

print("X shape:", X.shape)
print("y_reg shape:", y_reg.shape)
print("y_clf shape:", y_clf.shape)

X shape: (5633, 463)
y_reg shape: (5633,)
y_clf shape: (5633,)

In [48]:
main_targets_single = main_reduced.copy()

if 'ICS_40' in main_targets_single.columns:
    main_targets_single['ICS_40'] = main_targets_single['ICS_40'].replace(reserve_codes, np.nan)
    main_targets_single = main_targets_single[main_targets_single['ICS_40'].notna()].copy()

    y_single = main_targets_single['ICS_40']
    X_single = main_targets_single.drop(columns=['ICS_40'])

    print(X_single.shape)
    print(y_single.value_counts(dropna=False).sort_index())

(5619, 474)
ICS_40
1.0     785
2.0    1094
3.0    2346
4.0    1394
Name: count, dtype: int64